// In-memory demo dataset, shaped like the Supabase tables (snake_case columns).
// Lets the whole app run with no database. Mirrors sgas_mockup.html data.
// Mutations update this store so demo mode is fully interactive within a session.

export const store = {
  companies: [
    { company_id: 1, name: 'Fylde Heating Ltd', address: 'Unit 5 Squires Gate Lane, Blackpool, FY4 3RN', contact_name: 'Dave Marsh', phone: '01253 110011', email: 'accounts@fyldeheating.co.uk', sage_ref: 'SAGE-001', send_to_employer: true },
    { company_id: 2, name: 'Coastline Plumbing', address: '12 Marine Parade, Lytham, FY8 5LE', contact_name: 'Sarah Webb', phone: '01253 220022', email: 'sarah@coastlineplumbing.co.uk', sage_ref: 'SAGE-002', send_to_employer: true },
    { company_id: 3, name: 'J. Hartley (Sole Trader)', address: '8 Cornwall Avenue, Blackpool, FY2 9QS', contact_name: 'John Hartley', phone: '07700 900123', email: 'john.hartley@gmail.com', sage_ref: 'SAGE-003', send_to_employer: false },
    { company_id: 4, name: 'Northwest Renewables', address: 'Suite 3 Amy Johnson Way, Blackpool, FY4 2RP', contact_name: 'Priya Shah', phone: '01253 330033', email: 'priya@nwrenewables.co.uk', sage_ref: 'SAGE-004', send_to_employer: true },
  ],
  clients: [
    { client_id: 1, company_id: 1, ni_number: 'AB123456C', forename: 'Tom', surname: 'Ainsworth', date_of_birth: '1990-04-12', premise: '14', street: 'Hawthorn Road', town: 'Blackpool', district: '', county: 'Lancashire', postcode: 'FY1 4PT', mobile: '07700 900001', telephone: '', email: 'tom.a@example.com' },
    { client_id: 2, company_id: 1, ni_number: 'AB223456C', forename: 'Gary', surname: 'Bell', date_of_birth: '1985-09-30', premise: '42', street: 'Waterloo Road', town: 'Blackpool', district: '', county: 'Lancashire', postcode: 'FY4 1AB', mobile: '07700 900002', telephone: '', email: 'gary.b@example.com' },
    { client_id: 3, company_id: 2, ni_number: 'AB323456C', forename: 'Hassan', surname: 'Iqbal', date_of_birth: '1992-01-15', premise: '7', street: 'Clifton Drive', town: 'Lytham', district: '', county: 'Lancashire', postcode: 'FY8 5RA', mobile: '07700 900003', telephone: '', email: 'hassan.i@example.com' },
    { client_id: 4, company_id: 3, ni_number: 'AB423456C', forename: 'John', surname: 'Hartley', date_of_birth: '1978-07-22', premise: '8', street: 'Cornwall Avenue', town: 'Blackpool', district: '', county: 'Lancashire', postcode: 'FY2 9QS', mobile: '07700 900123', telephone: '', email: 'john.hartley@gmail.com' },
    { client_id: 5, company_id: 4, ni_number: 'AB523456C', forename: 'Megan', surname: 'Doyle', date_of_birth: '1995-11-03', premise: '21', street: 'Park Road', town: 'Poulton-le-Fylde', district: '', county: 'Lancashire', postcode: 'FY6 7AB', mobile: '07700 900005', telephone: '', email: 'megan.d@example.com' },
    { client_id: 6, company_id: 2, ni_number: 'AB623456C', forename: 'Liam', surname: 'Prentice', date_of_birth: '1988-03-19', premise: '3', street: 'Henry Street', town: 'Lytham', district: '', county: 'Lancashire', postcode: 'FY8 5LF', mobile: '07700 900006', telephone: '', email: 'liam.p@example.com' },
    { client_id: 7, company_id: 1, ni_number: 'AB723456C', forename: 'Owen', surname: 'Pugh', date_of_birth: '1991-06-08', premise: '56', street: 'Caunce Street', town: 'Blackpool', district: '', county: 'Lancashire', postcode: 'FY1 3NG', mobile: '07700 900007', telephone: '', email: 'owen.p@example.com' },
    { client_id: 8, company_id: 4, ni_number: 'AB823456C', forename: 'Rhys', surname: 'Evans', date_of_birth: '1993-02-27', premise: '9', street: 'Newton Drive', town: 'Blackpool', district: '', county: 'Lancashire', postcode: 'FY3 8LZ', mobile: '07700 900008', telephone: '', email: 'rhys.e@example.com' },
  ],
  // The `assessors` array is the shared STAFF list (anyone can be trainer/assessor/verifier).
  assessors: [
    { assessor_id: 1, name: 'S Johnston', assigned_room: 'Bay Block A', email: 's.johnston@sgas.test', teamup_subcalendar: 'sub_sjohnston', is_active: true },
    { assessor_id: 2, name: 'K Rimmer', assigned_room: 'Bay Block B', email: 'k.rimmer@sgas.test', teamup_subcalendar: 'sub_krimmer', is_active: true },
    { assessor_id: 3, name: 'A Calvert', assigned_room: 'Classroom 3', email: 'a.calvert@sgas.test', teamup_subcalendar: 'sub_acalvert', is_active: true },
    { assessor_id: 4, name: 'M Patel', assigned_room: 'Classroom 1', email: 'm.patel@sgas.test', teamup_subcalendar: 'sub_mpatel', is_active: true },
    { assessor_id: 5, name: 'D Okeke', assigned_room: 'Bay Block C', email: 'd.okeke@sgas.test', teamup_subcalendar: 'sub_dokeke', is_active: true },
  ],
  courses: [
    { course_id: 1, name: 'Domestic Gas ACS Initial', scheme: 'ACS Domestic', price: 1450, teamup_designator: 'ACS-DOM' },
    { course_id: 2, name: 'Domestic Gas ACS Reassessment', scheme: 'ACS Domestic', price: 950, teamup_designator: 'ACS-DOM-RE' },
    { course_id: 3, name: 'OFTEC Oil', scheme: 'OFTEC', price: 780, teamup_designator: 'OFTEC' },
    { course_id: 4, name: 'Commercial Gas ACS', scheme: 'ACS Commercial', price: 1650, teamup_designator: 'ACS-COM' },
    { course_id: 5, name: 'Air Source Heat Pump L3', scheme: 'Renewables', price: 1100, teamup_designator: 'ASHP' },
    { course_id: 6, name: 'LPG Changeover', scheme: 'LPG', price: 620, teamup_designator: 'LPG' },
    { course_id: 7, name: 'Catering Gas ACS', scheme: 'Catering', price: 1250, teamup_designator: 'CATER' },
    { course_id: 8, name: 'Electrical (18th Edition)', scheme: 'Electrical', price: 680, teamup_designator: 'ELEC' },
    { course_id: 9, name: 'Water & Plumbing', scheme: 'Water', price: null, teamup_designator: '' },
    { course_id: 10, name: 'F-Gas / Air Conditioning', scheme: 'F-gas', price: null, teamup_designator: '' },
    { course_id: 11, name: 'Solid Fuel', scheme: 'Solid Fuel', price: null, teamup_designator: '' },
    { course_id: 12, name: 'Gas Metering', scheme: 'Meters', price: null, teamup_designator: '' },
    { course_id: 13, name: 'Commercial Laundry', scheme: 'Laundry', price: null, teamup_designator: '' },
    { course_id: 14, name: 'Emergency Service & Metering', scheme: 'ESP', price: null, teamup_designator: '' },
    { course_id: 15, name: 'I-GAS Industrial Gas Accreditation', scheme: 'IGAS', price: null, teamup_designator: '' },
    { course_id: 16, name: 'Industrial / Non-Domestic Gas', scheme: 'Industrial', price: null, teamup_designator: '' },
    { course_id: 17, name: 'Limited Scope Commercial Gas', scheme: 'Limited Scope', price: null, teamup_designator: '' },
  ],
  categories: [
    c(1, 'CCN1', 'Core Domestic Gas Safety', 'ACS Domestic', 5),
    c(2, 'CENWAT', 'Central Heating Boilers & Water Heaters', 'ACS Domestic', 5),
    c(3, 'CKR1', 'Domestic Cookers', 'ACS Domestic', 5),
    c(4, 'HTR1', 'Gas Fires & Wall Heaters', 'ACS Domestic', 5),
    c(5, 'DAH1', 'Ducted Air Heaters', 'ACS Domestic', 5),
    c(6, 'LAU1', 'Domestic Laundry (Tumble Dryers)', 'ACS Domestic', 5),
    c(7, 'LE1', 'Leisure / Caravan Appliances', 'ACS Domestic', 5),
    c(8, 'CKHB1', 'Cooker & Hob (Domestic)', 'ACS Domestic', 5),
    c(9, 'DFDA1', 'Domestic Flueless Appliances', 'ACS Domestic', 5),
    c(10, 'HWB1', 'Domestic Hot Water Boilers', 'ACS Domestic', 5),
    c(11, 'WAT1', 'Instantaneous Water Heaters', 'ACS Domestic', 5),
    c(12, 'CHDDA1', 'Domestic Ducted Air / Warm Air', 'ACS Domestic', 5),
    c(13, 'CoCDN1', 'Changeover Domestic (Natural Gas)', 'ACS Domestic', 5),
    c(14, 'CoLPNG1', 'Changeover LPG to Natural Gas', 'ACS Domestic', 5),
    c(15, 'COCN1', 'Core Commercial Gas Safety', 'ACS Commercial', 5),
    c(16, 'CoDNCO1', 'Changeover Domestic to Commercial', 'ACS Commercial', 5),
    c(17, 'CORT1', 'Commercial Heating & Plant', 'ACS Commercial', 5),
    c(18, 'CIGA1', 'Commercial Industrial Gas Appliances', 'ACS Commercial', 5),
    c(19, 'ICPN1', 'Commercial Pipework', 'ACS Commercial', 5),
    c(20, 'CDGA1', 'Commercial Direct-Fired Appliances', 'ACS Commercial', 5),
    c(21, 'CGFE1', 'Commercial Gas Fired Equipment', 'ACS Commercial', 5),
    c(22, 'OCP1', 'Commercial Overpressure / Boosters', 'ACS Commercial', 5),
    c(23, 'BMP1', 'Commercial Boosters & Compressors', 'ACS Commercial', 5),
    c(24, 'TPCP1', 'Tightness Testing & Purging (Domestic)', 'ACS Commercial', 5),
    c(25, 'TPCP1A', 'Tightness Testing & Purging (Commercial)', 'ACS Commercial', 5),
    c(26, 'CoCNPILS', 'Core Commercial Pipework (Limited Scope)', 'Limited Scope', 5),
    c(27, 'ICPNLS', 'Commercial Pipework (Limited Scope)', 'Limited Scope', 5),
    c(28, 'ICAELS', 'Commercial Appliances (Limited Scope)', 'Limited Scope', 5),
    c(29, 'MET1', 'Domestic Gas Meters', 'Meters', 5),
    c(30, 'MET2', 'Medium Pressure Meters', 'Meters', 5),
    c(31, 'MET3LS', 'Meters (Limited Scope)', 'Meters', 5),
    c(32, 'MET4', 'Large / Industrial Meters', 'Meters', 5),
    c(33, 'CMET1', 'Commercial Meters', 'Meters', 5),
    c(34, 'CMET2', 'Commercial Meters (Medium Pressure)', 'Meters', 5),
    c(35, 'REGT1', 'Gas Regulators', 'Meters', 5),
    c(36, 'CCLNG1', 'Commercial Laundry (Natural Gas)', 'Laundry', 5),
    c(37, 'CoCCLNG1', 'Changeover Commercial Laundry NG', 'Laundry', 5),
    c(38, 'CLE1', 'Commercial Laundry Equipment', 'Laundry', 5),
    c(39, 'CONGLP1PD', 'LPG Changeover — Permanent Dwellings', 'LPG', 5),
    c(40, 'CONGLP1LAV', 'LPG Changeover — Leisure Accommodation Vehicles', 'LPG', 5),
    c(41, 'CONGLP1RPH', 'LPG Changeover — Residential Park Homes', 'LPG', 5),
    c(42, 'CONGLP1B', 'LPG Changeover — Boats', 'LPG', 5),
    c(43, 'CONGLP1CMC', 'LPG Changeover — Commercial', 'LPG', 5),
    c(44, 'CCLP1PD', 'LPG Core — Permanent Dwellings', 'LPG', 5),
    c(45, 'CCLP1LAV', 'LPG Core — Leisure Accommodation Vehicles', 'LPG', 5),
    c(46, 'CCLP1RPH', 'LPG Core — Residential Park Homes', 'LPG', 5),
    c(47, 'CCLP1B', 'LPG Core — Boats', 'LPG', 5),
    c(48, 'CCLP1MC', 'LPG Core — Mobile Catering', 'LPG', 5),
    c(49, 'CCLP1EP', 'LPG Core — Engineered Pipework', 'LPG', 5),
    c(50, 'CCLP1EPC', 'LPG Core — Engineered Pipework Commercial', 'LPG', 5),
    c(51, 'CCLPCMC', 'LPG Core — Commercial', 'LPG', 5),
    c(52, 'HTRLP1', 'LPG Heaters 1', 'LPG', 5),
    c(53, 'HTRLP2', 'LPG Fires & Heaters', 'LPG', 5),
    c(54, 'HTRLP3', 'LPG Heaters 3', 'LPG', 5),
    c(55, 'WATLP2', 'LPG Water Heaters', 'LPG', 5),
    c(56, 'REFLP1', 'LPG Refrigerators', 'LPG', 5),
    c(57, 'WAHLP1', 'LPG Warm Air Heaters', 'LPG', 5),
    c(58, 'EFJLP1', 'LPG Flueless / Jet Appliances', 'LPG', 5),
    c(59, 'VESLP1', 'LPG Vessels 1', 'LPG', 5),
    c(60, 'VESLP2', 'LPG Vessels 2', 'LPG', 5),
    c(61, 'CABLP1', 'LPG Cabinet Heaters', 'LPG', 5),
    c(62, 'OGLP1', 'LPG Other Gas Appliances', 'LPG', 5),
    c(63, 'CESP1', 'Core Emergency Service Provider', 'ESP', 5),
    c(64, 'CMA1', 'Emergency Meter / Gas Escapes', 'ESP', 5),
    c(65, 'CMA2LS', 'Emergency Meter (Limited Scope)', 'ESP', 5),
    c(66, 'CCCN1', 'Core Commercial Catering Gas Safety', 'Catering', 5),
    c(67, 'CODC1', 'Commercial Catering — Direct', 'Catering', 5),
    c(68, 'COCAT1', 'Commercial Catering — Core', 'Catering', 5),
    c(69, 'COMCAT1', 'Commercial Catering — Core Appliances', 'Catering', 5),
    c(70, 'COMCAT2', 'Catering — Ovens & Ranges', 'Catering', 5),
    c(71, 'COMCAT3', 'Catering — Boiling & Steaming', 'Catering', 5),
    c(72, 'COMCAT4', 'Catering — Griddles & Fryers', 'Catering', 5),
    c(73, 'COMCAT5', 'Catering — Appliance Installation', 'Catering', 5),
    c(74, 'OFTEC101', 'Oil — Domestic Pressure Jet', 'OFTEC', 5),
    c(75, 'OFTEC102', 'Oil — Vaporising / Wallflame', 'OFTEC', 5),
    c(76, 'OFTEC105E', 'Oil — Tank Installation & Siting', 'OFTEC', 5),
    c(77, 'OFTEC600A', 'Oil — Cookers & Range', 'OFTEC', 5),
    c(78, 'OFTEC201', 'Oil — Commercial / Pressure Jet >45kW', 'OFTEC', 5),
    c(79, 'OFTEC108', 'Solid Fuel — Appliances', 'Solid Fuel', 5),
    c(80, 'SOLAR-PV', 'Solar Photovoltaic Installation', 'Renewables', 5),
    c(81, 'SOLAR-TH', 'Solar Thermal Hot Water', 'Renewables', 5),
    c(82, 'GSHP', 'Ground Source Heat Pump Installation', 'Renewables', 5),
    c(83, 'ASHP', 'Air Source Heat Pump Installation', 'Renewables', 5),
    c(84, 'IGAS1', 'IGAS Level 1', 'IGAS', 5),
    c(85, 'IGAS2', 'IGAS Level 2', 'IGAS', 5),
    c(86, 'IGAS3', 'IGAS Level 3', 'IGAS', 5),
    c(87, 'LC-NDGSPG(CPD)', 'Non-Domestic Gas Pipework (CPD)', 'Industrial', 5),
    c(88, 'LC-NDGSPG(TEC)', 'Non-Domestic Gas Pipework (TEC)', 'Industrial', 5),
    c(89, 'LC-BOMSA', 'Burner & Boiler Management Systems', 'Industrial', 5),
    c(90, 'LC-NDGSA(CPD)', 'Non-Domestic Gas Appliances (CPD)', 'Industrial', 5),
    c(91, 'LC-NDGSBC(CPD)', 'Non-Domestic Boilers Combustion (CPD)', 'Industrial', 5),
    c(92, 'LC-NDGSBC(TEC)', 'Non-Domestic Boilers Combustion (TEC)', 'Industrial', 5),
    c(93, 'LC-NDGSBG(TEC)', 'Non-Domestic Gas Boilers (TEC)', 'Industrial', 5),
    c(94, 'LC-NDGSABGS(CPD)', 'Non-Domestic Appliances & Boilers (CPD)', 'Industrial', 5),
    c(95, 'LO-IGUB(TEC)', 'Industrial Gas Utilisation Burners (TEC)', 'Industrial', 5),
    c(96, 'LO-ADB(TEC)', 'Atmospheric & Diffusion Burners (TEC)', 'Industrial', 5),
    c(97, 'CHPP(G)', 'Combined Heat & Power (Gas)', 'Industrial', 5),
    c(98, 'HWSAFETY', 'Hot Water Safety', 'Water', null),
    c(99, 'WRAS', 'Water Regulations (WRAS)', 'Water', null),
    c(100, 'LEGION', 'Legionella Prevention', 'Water', null),
    c(101, 'LTHW', 'Low Temp Heating / Hot Water Systems', 'Water', null),
    c(102, 'BS7671', '18th Edition Wiring Regulations', 'Electrical', null),
    c(103, 'DEI', 'Domestic Electrical Installer', 'Electrical', null),
    c(104, 'INSP', 'Inspection & Testing', 'Electrical', null),
    c(105, 'ENEFF', 'Energy Efficiency', 'Other', null),
    c(106, 'FGAS', 'F-Gas / Air Conditioning', 'F-gas', null),
    c(107, 'GL8', 'GL8 (Gas Leak / Network)', 'Other', null),
    c(108, 'AOOP123', 'AOOP 123', 'Other', null),
    c(109, 'CMA3', 'Emergency Meter / Network 3', 'Other', 5),
    c(110, 'CPA1', 'Combustion Performance Analysis', 'ACS Domestic', 5),
  ],
  // A `session` is a course BLOCK (course + dates). Roles come from the staff list.
  // Blocks 5 & 6 are freshly "pulled from Teamup" — no staff assigned yet.
  sessions: [
    s(1, 1, '2026-06-15', '2026-06-17', 'tu-1', 4, 1, 2),
    s(2, 1, '2026-06-22', '2026-06-26', 'tu-2', 4, 2, 3),
    s(3, 3, '2026-07-01', '2026-07-02', 'tu-3', 4, 1, 2),
    s(4, 5, '2026-07-06', '2026-07-10', 'tu-4', 5, 3, 2),
    s(5, 1, '2026-07-13', '2026-07-15', 'tu-5', null, null, null),
    s(6, 5, '2026-07-20', '2026-07-24', 'tu-6', null, null, null),
  ],
  bookings: [
    bk(1, 1, 1, 1, false, false, false, null),
    { ...bk(2, 2, 1, 1, false, false, true, null), is_reassessment: true },
    { ...bk(3, 3, 2, 2, false, false, false, null), disposition: 'NYC' },
    bk(4, 4, 3, 3, false, false, false, null),
    bk(5, 5, 4, 4, false, false, false, null),
    { ...bk(6, 6, 2, 2, false, false, false, null), disposition: 'NO_SHOW' },
    // §4.10 demo: Tom (client 1) is re-booked for CCN1 → that qual drops off his renewal list.
    bk(7, 1, 5, 1, false, false, false, null),
  ],
  booking_categories: [
    bc(1, 1, 1, 'PASS', '2021-07-01', '2026-07-01'),
    bc(2, 1, 2, 'PASS', '2021-07-01', '2026-07-01'),
    bc(3, 2, 1, 'PASS', '2021-07-16', '2026-07-16'),
    bc(4, 2, 3, 'PENDING', null, null),
    bc(5, 3, 1, 'PENDING', null, null),
    bc(6, 3, 2, 'PENDING', null, null),
    bc(7, 3, 4, 'PENDING', null, null),
    bc(8, 4, 74, 'PASS', '2023-07-01', '2028-07-01'),
    bc(9, 5, 83, 'PENDING', null, null),
    bc(10, 6, 1, 'PASS', '2026-05-20', '2031-05-20'),
    bc(11, 6, 3, 'FAIL', null, null),
    bc(12, 6, 4, 'PENDING', null, null),
    bc(13, 7, 1, 'PENDING', null, null), // Tom's CCN1 re-booking (booked-in → drops off renewals)
  ],
  pool: [
    { id: 101, client_id: 3, scheme: 'ACS Domestic', category_ids: [1, 2, 4], prefFrom: '2026-07-13', prefTo: '2026-07-24' },
    { id: 102, client_id: 6, scheme: 'ACS Domestic', category_ids: [1, 3], prefFrom: '2026-07-20', prefTo: '2026-07-31' },
    { id: 103, client_id: 7, scheme: 'ACS Domestic', category_ids: [1, 2], kind: 'MIXED', cat_kinds: { 1: 'REASSESS', 2: 'NEW' } },
    { id: 104, client_id: 1, scheme: 'ACS Domestic', category_ids: [1], kind: 'REASSESS', prefFrom: '2026-07-13', prefTo: '2026-07-15' },
    { id: 105, client_id: 2, scheme: 'ACS Domestic', category_ids: [1, 2], mlp: true, igas: true },
    { id: 106, client_id: 4, scheme: 'OFTEC', category_ids: [74, 76] },
    { id: 107, client_id: 5, scheme: 'Renewables', category_ids: [83], kind: 'REASSESS' },
    { id: 108, client_id: 8, scheme: 'Renewables', category_ids: [83, 80] },
  ],
  users: [
    { user_id: 1, username: 'admin', name: 'Demo Admin', email: 'admin@sgas.test', role: 'ADMIN', is_active: true,
      password_salt: 'e318c2be7e8a2a2598ac755bae720ed9', password_hash: '5791ef2a85f8848df500f67c6facab5ab082ccb20d1053469117a4cf162ed29b' },
    { user_id: 2, username: 'reception', name: 'Demo Reception', email: 'reception@sgas.test', role: 'STANDARD', is_active: true,
      password_salt: 'c29dc5a8cbffb68c04bea479eed04f38', password_hash: '17e7e58f9ab7263374e79fc976a2dcab16366c58bf5d6f3a478b1468ff9b4210' },
    // All demo accounts share password 'demo' (same salt/hash as reception).
    { user_id: 3, username: 'scheduler', name: 'Demo Scheduler', email: 'scheduler@sgas.test', role: 'SCHEDULER', is_active: true,
      password_salt: 'c29dc5a8cbffb68c04bea479eed04f38', password_hash: '17e7e58f9ab7263374e79fc976a2dcab16366c58bf5d6f3a478b1468ff9b4210' },
    { user_id: 4, username: 'assessor', name: 'Demo Assessor', email: 'assessor@sgas.test', role: 'ASSESSOR', is_active: true,
      password_salt: 'c29dc5a8cbffb68c04bea479eed04f38', password_hash: '17e7e58f9ab7263374e79fc976a2dcab16366c58bf5d6f3a478b1468ff9b4210' },
    { user_id: 5, username: 'accounts', name: 'Demo Accounts', email: 'accounts@sgas.test', role: 'ACCOUNTS', is_active: true,
      password_salt: 'c29dc5a8cbffb68c04bea479eed04f38', password_hash: '17e7e58f9ab7263374e79fc976a2dcab16366c58bf5d6f3a478b1468ff9b4210' },
  ],
  chase_log: [
    { chase_id: 1, booking_id: 2, chased_at: '2026-06-02T09:15:00Z', items: 'Payment', channel: 'email' },
  ],
  // §4.10 demo: Gary (client 2) has had 5 unanswered renewal emails for CCN1 → cold list (phone follow-up).
  renewal_contact: [
    { renewal_contact_id: 1, client_id: 2, category_code: 'CCN1', sent_at: '2026-04-20T09:00:00Z', channel: 'email' },
    { renewal_contact_id: 2, client_id: 2, category_code: 'CCN1', sent_at: '2026-04-28T09:00:00Z', channel: 'email' },
    { renewal_contact_id: 3, client_id: 2, category_code: 'CCN1', sent_at: '2026-05-06T09:00:00Z', channel: 'email' },
    { renewal_contact_id: 4, client_id: 2, category_code: 'CCN1', sent_at: '2026-05-15T09:00:00Z', channel: 'email' },
    { renewal_contact_id: 5, client_id: 2, category_code: 'CCN1', sent_at: '2026-05-25T09:00:00Z', channel: 'email' },
    { renewal_contact_id: 6, client_id: 2, category_code: 'CCN1', sent_at: '2026-06-08T14:30:00Z', channel: 'phone', notes: 'No reply — left voicemail' },
  ],
  // Tom Ainsworth (client 1) is on an MLP of 3 courses; he's passed Domestic (course 1).
  mlps: [
    { mlp_id: 1, client_id: 1, label: 'Gas new-entrant MLP', created_at: '2026-05-01T09:00:00Z', completed_at: null },
  ],
  mlp_courses: [
    { mlp_course_id: 1, mlp_id: 1, course_id: 1 },
    { mlp_course_id: 2, mlp_id: 1, course_id: 3 },
    { mlp_course_id: 3, mlp_id: 1, course_id: 5 },
  ],
  inquiries: [
    { inquiry_id: 1, name: 'Dave Stott', email: 'dave.stott@example.com', mobile: '07700 900111', courses: 'Domestic Gas ACS, LPG', pref_date_from: '2026-07-13', pref_date_to: '2026-07-24', notes: 'Ticket runs out soon — also asked about CPA1.', status: 'open', created_at: '2026-06-24T10:12:00Z', handled_at: null },
    { inquiry_id: 2, name: 'Sue', email: '', mobile: '07700 900222', courses: 'Commercial Catering', pref_date_from: null, pref_date_to: null, notes: 'Name + number only — wants a callback with prices.', status: 'open', created_at: '2026-06-25T15:40:00Z', handled_at: null },
  ],
  seq: { client: 8, company: 4, course: 17, cat: 110, session: 6, booking: 7, bcat: 13, pool: 108, user: 5, staff: 5, chase: 1, mlp: 1, mlpc: 3, renewal: 6, inquiry: 2 },
}

export const ASSESSOR_COLOR = { 1: '#0a5ad6', 2: '#1a8a4b', 3: '#9a3fb5', 4: '#b7791f', 5: '#0a7d63' }

function c(id, code, description, scheme, renewal_years) {
  return { category_id: id, code, description, scheme, renewal_years }
}
function s(id, course_id, start_date, end_date, teamup_event_id, trainer_id, assessor_id, verifier_id) {
  return { session_id: id, course_id, start_date, end_date, teamup_event_id, trainer_id, assessor_id, verifier_id }
}
function bk(id, client_id, session_id, company_id, flag_mlp, flag_igas, flag_payment_outstanding, last_chased) {
  return {
    booking_id: id, client_id, session_id, company_id,
    overall_result: 'PENDING', disposition: 'NONE', assess_notes: null,
    flag_mlp, flag_igas, flag_payment_outstanding,
    flag_cert_outstanding: false, flag_photo_outstanding: false, sage_ref: null,
    is_reassessment: false, pref_date_from: null, pref_date_to: null, rescheduled: false,
    igas_evidence_date: null, last_chased, confirmation_sent_at: null,
  }
}
function bc(id, booking_id, category_id, result, achieved_date, expiry_date, reassess = false) {
  return { booking_category_id: id, booking_id, category_id, result, achieved_date, expiry_date, is_reassessment: reassess }
}
